require('config.options')
require('config.plugins')
require('config.mini')
require('config.tree')
require('config.telescope')
-- require('config.drop')
require('config.treesitter')
require('config.lsp')
require('config.keymaps')
require('config.autocmds')
