require('config.options')
require('config.plugins')
require('config.mini')
require('config.smear-cursor')
require('config.tree')
require('config.telescope')
require('config.gitsigns')
require('config.satellite')
require('config.diffview')
-- require('config.drop')
require('config.treesitter')
require('config.lsp')
require('config.keymaps')
require('config.autocmds')
